version: '2'

services:
  database:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - postgres:/data/db
    ports:
      - 5432:5432
  web:
    build:
      context: sql_app
      dockerfile: Dockerfile
    container_name: web
    network_mode: host
    ports:
      - 8000:8000
    depends_on:
      - database
volumes:
  postgres: